### ISSUE TITLE
Linter incorrectly suggests to use range over int for string which is modified inside for loop.

### ISSUE THREAD

**Issue by DmitriyMV** [ckaznocha/intrange#12]
**Describe the bug**

Linter incorrectly suggests to use range over int for string which is modified inside for loop.

**To Reproduce**

Run linter on this piece of code:

```go
package main

import "fmt"

func trim(what string) string {
	for i := 0; i < len(what); i++ {
		if what[i] == 'v' && i+1 < len(what) && what[i+1] >= '0' && what[i+1] <= '9' {
			what = what[:i] + what[i+1:]
		}
	}

	return what
}

func main() {
	fmt.Println(trim("v1.2.3"))
}
```

**Expected behavior**
Linter doesn't suggest  to use `for i := range len(what)` since `what` is modified inside and `len(what)` needs to be evaluated on each iteration (`range` expression doesn't do that per spec)`.

**Comment by ckaznocha** [comment]
Thanks for reporting, this applies to anything where the right side gets modified in the loop.

**Comment by ckaznocha** [comment]
Of course this also applies when the right side is a side-effect as seen in #13 but I'm going to treat that as a special case.
