### ISSUE TITLE
Old benchmark loop should be detected

### ISSUE THREAD

**Issue by pierrre** [ckaznocha/intrange#31]
**Describe the bug**
Benchmark loop using the old syntax `for i := 0; i < b.N; i++ ` should be detected.

**To Reproduce**
Write a benchmark loop with `for i := 0; i < b.N; i++ `.

**Expected behavior**
The linter should suggest to rewrite to `for range b.N`

**Additional context**
Related to https://github.com/ckaznocha/intrange/issues/13

**Comment by pierrre** [comment]
https://github.com/ckaznocha/intrange/issues/13#issuecomment-2366916821
>  I think the proper solution here is to expose a setting to exclude patterns.

What kind of pattern do you have in mind ?
Do you want to match `b.N` or the entire line ?

**Comment by ckaznocha** [comment]
I was thinking the whole for statement (sans body) but I'm really not settled one way or another, do you have opinions?

**Comment by pierrre** [comment]
> I was thinking the whole for statement (sans body)

looks good :+1:
