### ISSUE TITLE
Support for i <= n

### ISSUE THREAD

**Issue by ccoVeille** [ckaznocha/intrange#38]
The pattern is not common, but what about detecting

```go
for i := 0 ; i <= 9 ; i++ {

}
```

and suggest fixing it with

```go
for i := range 10 {

}
```

Here are some examples

https://github.com/search?q=%22for+i+%3A%3D+0+%3B+i+%3C%3D+5+%3B+i%2B%2B+%7B%22+language%3Ago&type=code
https://github.com/search?q=%22for+i+%3A%3D+0+%3B+i+%3C%3D+10+%3B+i%2B%2B+%7B%22+language%3Ago&type=code

**Comment by ckaznocha** [comment]
yup this should get caught!
